### ISSUE TITLE
Html attribute filters dont work

### ISSUE THREAD

**Issue by drnkwati** [snebes/html-sanitizer#15]
Hi
I tried to use allowed_attributes filters by setting configuration for specific tags as 
in the original docs from here
https://github.com/tgalopin/html-sanitizer/blob/master/docs/3-configuration-reference.md
but it did not work.
Is this feature removed? 
Are they any other options i can use to configure the sanitizer.

thanks

**Comment by snebes** [comment]
Can you provide a sample of your extension/configuration?

This is an example config for `del` and `br` that I use that covers all options:

```
                'br'         => [
                    'allowed_attributes' => [],
                    'childless'          => true,
                ],
                'del'        => [
                    'convert_elements'   => ['s'],
                    'allowed_attributes' => ['class'],
                    'allowed_classes'    => [
                        'diff-html-removed',
                        'diff-image-removed',
                    ],
                ],
```

`allowed_attributes` should be an array of strings that represent valid attributes.

`allowed_attributes` should be an array of strings of valid class names.  `class` would need to be included in `allowed_attributes` as well.

`childless` is a boolean

`convert_elements` is used to convert the deprecated `s` tag into a `del` tag.

**Comment by snebes** [comment]
Here is a full sample custom Extension showing how the above is implemented:

```
<?php

declare(strict_types=1);

namespace Sample;

use SN\HtmlSanitizer\Extension\ExtensionInterface;
use SN\HtmlSanitizer\NodeVisitor\NodeVisitorInterface;
use SN\HtmlSanitizer\NodeVisitor\RemoveNodeVisitor;
use SN\HtmlSanitizer\NodeVisitor\TagNodeVisitor;

class SampleExtension implements ExtensionInterface
{
    /**
     * @return string
     */
    public function getName(): string
    {
        return 'sample';
    }

    /**
     * @param array $config
     * @return NodeVisitorInterface[]
     */
    public function createNodeVisitors(array $config = []): array
    {
        $defaultTagConfig = [
            'allowed_attributes' => [],
        ];

        $defaultConfig = [
            'tags' => [
                // more tags defined...
                'br'         => [
                    'allowed_attributes' => [],
                    'childless'          => true,
                ],
                'del'        => [
                    'convert_elements'   => ['s'],
                    'allowed_attributes' => ['class'],
                    'allowed_classes'    => [
                        'diff-html-removed',
                        'diff-image-removed',
                    ],
                ],
            ],
        ];

        $tags = [];

        foreach ($defaultConfig['tags'] as $tag => $tagConfig) {
            $tags[$tag] = new TagNodeVisitor($tag, $tagConfig);
        }

        // Removed tags.
        $tags['script'] = new RemoveNodeVisitor('script');
        $tags['style'] = new RemoveNodeVisitor('style');

        return $tags;
    }
}
```

**Comment by drnkwati** [comment]
thanks I fixed my code. Your examples were very helpful.
Below is a modification i did for the Html5Extension in my own fork. 
`
    public function createNodeVisitors(array $config = array())
    {
        $globalOptions = array(
            'allowed_attributes', 'allowed_classes',
            'blocked_attributes', 'blocked_classes',
            'childless', 'convert_elements',
        );

        $tagConfigs = $this->getDefaultConfig();

        foreach ($tagConfigs as $tag => $tagConfig) {
            //
            if ((isset($config['tags_allowed']) && !in_array($tag, $config['tags_allowed'])) ||
                (isset($config['tags_disallowed']) && in_array($tag, $config['tags_disallowed']))) {
                unset($tagConfigs[$tag]);
                continue;
            }

            // global options
            foreach ($globalOptions as $option) {
                if (isset($config[$option])) {
                    $tagConfig[$option] = array_unique(array_merge(
                        isset($tagConfig[$option]) ? $tagConfig[$option] : array(), $config[$option]
                    ));
                }
            }

            $tagConfigs[$tag] = new TagNodeVisitor($tag, $tagConfig);
        }

        return $tagConfigs;
    }

    /**
     * @return array
     */
    public function getDefaultConfig()
    {
        return array(
            // Main root
            'html' => array(),

            // Document metadata
            'base' => array('childless' => true),
            'head' => array(),
            'link' => array('childless' => true),
            'meta' => array('childless' => true),
            'style' => array(),
            'title' => array(),

            // Sectioning root
            'body' => array(),

            // Content sectioning
            'address' => array(),
            'article' => array(),
            'aside' => array(),
            'footer' => array(),
            'header' => array(),
            'h1' => array(),
            'h2' => array(),
            'h3' => array(),
            'h4' => array(),
            'h5' => array(),
            'h6' => array(),
            'hgroup' => array(),
            'main' => array(),
            'nav' => array(),
            'section' => array(),

            // Text content
            'blockquote' => array(),
            'dd' => array(),
            'dir' => array(),
            'div' => array(),
            'dl' => array(),
            'dt' => array(),
            'figcaption' => array(),
            'figure' => array(),
            'hr' => array('childless' => true),
            'li' => array(),
            'ol' => array(),
            'ul' => array(),
            'p' => array(),
            'pre' => array(),

            // Inline text semantics
            'a' => array(),
            'abbr' => array(),
            'b' => array(),
            'bdi' => array(),
            'bdo' => array(),
            'br' => array('childless' => true),
            'cite' => array(),
            'code' => array(),
            'data' => array(),
            'dfn' => array(),
            'em' => array(),
            'i' => array(),
            'kbd' => array(),
            'mark' => array(),
            'q' => array(),
            'rb' => array(),
            'rp' => array(),
            'rt' => array(),
            'rtc' => array(),
            'ruby' => array(),
            's' => array(),
            'samp' => array(),
            'small' => array(),
            'span' => array(),
            'strong' => array(),
            'sub' => array(),
            'sup' => array(),
            'time' => array(),
            'tt' => array(),
            'u' => array(),
            'var' => array(),
            'wbr' => array('childless' => true),

            // Image and multimedia
            'area' => array('childless' => true),
            'audio' => array(),
            'img' => array('childless' => true),
            'map' => array(),
            'track' => array('childless' => true),
            'video' => array(),

            // Embedded content
            'applet' => array(),
            'embed' => array(),
            'iframe' => array(),
            'noembed' => array(),
            'object' => array(),
            'param' => array('childless' => true),
            'picture' => array(),
            'source' => array(),

            // Scripting
            'canvas' => array(),
            'noscript' => array(),
            'script' => array(),

            // Demarcating edits
            'del' => array(),
            'ins' => array(),

            // Table content
            'caption' => array(),
            'col' => array('childless' => true),
            'colgroup' => array(),
            'table' => array(),
            'tbody' => array(),
            'td' => array(),
            'tfoot' => array(),
            'th' => array(),
            'thead' => array(),
            'tr' => array(),

            // Forms
            'button' => array(),
            'datalist' => array(),
            'fieldset' => array(),
            'form' => array(),
            'input' => array('childless' => true),
            'label' => array(),
            'legend' => array(),
            'meter' => array(),
            'optgroup' => array(),
            'option' => array(),
            'output' => array(),
            'progress' => array(),
            'select' => array(),
            'textarea' => array(),

            // Interactive elements
            'details' => array(),
            'dialog' => array(),
            'menu' => array(),
            'menuitem' => array(),
            'summary' => array(),

            // Web Components
            'content' => array(),
            'element' => array(),
            'shadow' => array(),
            'slot' => array(),
            'template' => array(),
        );
    }
}
`
